### ISSUE TITLE
Asset urls in .scss.liquid files are not being served up via localhost

### ISSUE THREAD

**Issue by johnnietheblack** [Shopify/slate#696] opened 2018-08-02 06:30 UTC
### Problem

If I try to use an asset in the /assets/images directory as a background image in my `theme.scss.liquid` file, the parser doesn't recognize it the same way it would if I use that same asset in the `theme.liquid` file, and therefore it doesn't serve the url in the CSS file as a localhost url. Instead, it uses the Shopify url for the asset (but the asset hasn't been uploaded to Shopify, yet).

### Replication steps

1. Put an image in the `/assets/images` directory
2. Reference the image as a background-image in an .scss.liquid file
3. Check the url on the rendered page (it won't be localhost).

### More Information

I have tried this multiple times, with different file types, and I have looked through previous tickets to see if this is common - however, I've only seen similar requests in regards to referencing asset urls in `<img>` tags.

**Comment by joemallory** [comment] 2018-08-03 00:37
Having the same issue with the scss files.

**Comment by nutsynalinda** [comment] 2018-08-04 01:42
Had the same problem, used theme settings add image via page admin to over come it

background-image: url({{ settings.background-image-1 | img_url: '400x' }});

**Comment by ButsAndCats** [comment] 2018-08-07 01:36
I think this issue can be fixed by specifying an `img_url` filter

**Comment by johnnietheblack** [comment] 2018-08-07 02:25
Could you give an example?

**Comment by tauthomas01** [comment] 2018-08-07 19:57
Hi @johnnietheblack ,

As a temporary fix, you could put your images in the `assets/static` folder and reference it in your  `.scss.liquid` file such as this example : 

`background: url(#{'{{ "image_test2.jpg" | asset_img_url: "300x" }}'}) repeat 0 0;`

Where my `assets/static` folder contains `image_test2.jpg` file.

Make sure you run `yarn start` or `yarn deploy` when you make any changes in the `assets` folder.
It's a known issue (ref: https://github.com/Shopify/slate/issues/687) and we'll make sure this gets fixed soon.

I hope it helps.

**Comment by johnnietheblack** [comment] 2018-08-07 21:48
I had to run `yarn deploy` to get the asset to upload, but this ended up working as a temporary fix.

**Comment by t-kelly** [comment] 2018-08-08 18:08
Going to close this as it is a duplicate of https://github.com/Shopify/slate/issues/626. Please continue the conversation there if you have anything else to contribute.

**Closed by t-kelly** 2018-08-08 18:08 UTC

**Comment by gabyhernan** [comment] 2018-10-03 22:50
uploading the images to assets/statics worked as temp fix for me  and then doing yarn  deploy  but instead of having the css like that, this was the way it worked for me 

instead of this 
` background: url(#{'{{ "image_test2.jpg" | asset_img_url: "300x" }}'}) repeat 0 0;`

this what was worked for me 
 `   background-image: url('{{ "image_name.jpg" | asset_img_url: "300x" }}');`
