### ISSUE TITLE
How to import css file

### ISSUE THREAD

**Issue by ansarizafar** [Shopify/slate#133] opened 2017-04-23 08:18 UTC
I am trying to import semantic.css [(Semantic-ui)](semantic-ui.com) file from styles/vendor folder in theme.scss file but I am getting error in browser console file not theme.scss.css file not found

**Comment by adrhumphreys** [comment] 2017-04-23 22:06
@ansarizafar can you show us the code you're using to try an accomplish this? It really helps to try and solve it

**Comment by ansarizafar** [comment] 2017-04-24 01:35
@adrhumphreys I have not made any change in code. Here are the steps to reproduce the issue.

Slate theme test
Rename and update config.sample.yml
```
development:
  password: b261a6ca7a8ad449d80bcd34e89db450
  theme_id: "171030868"
  store: "24sevenbattery.myshopify.com"
  ignore_files:

production:
  password: b261a6ca7a8ad449d80bcd34e89db450
  theme_id: "171030932"
  store: "24sevenbattery.myshopify.com"
  ignore_files:
```
Copy semantic.css to src/styles/vendor folder
Impport semantic.css file in theme.scss file
```
@import url('vendor/semantic.css');
```
slate build
slate start
Here is the error in browser console
```
https://cdn.shopify.com/s/files/1/1941/3749/t/2/assets/theme.scss.css?16730064958607135614 Failed to load resource: the server responded with a status of 422 ()
```
If I remove css from theme.scss link tag evering thing works
```
//cdn.shopify.com/s/files/1/1941/3749/t/2/assets/theme.scss?16730064958607135614
```

**Comment by garethjohnsdesign** [comment] 2017-04-24 17:52
Having the same issue here, with trying to use Foundation CSS

**Comment by infernalsirius** [comment] 2017-04-26 07:01
I am having the same issue that @ansarizafar is experiencing. I added the css files to styles/vendor/semantic-css/semantic.min.css.

In styles/theme.scss I added this line: @import url('vendor/semantic-css/semantic.min.css');

**Comment by infernalsirius** [comment] 2017-04-26 08:54
I've been playing around a bit and I've been able to get this message:

> 	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders

This could be why we can't get it. Semantic UI has subfolders...

**Comment by infernalsirius** [comment] 2017-04-26 09:09
Shopify's CDN is limiting subfolders: https://ecommerce.shopify.com/c/ecommerce-design/t/subdirectories-under-assets-159090

I will make some changes and see if this is really the issue.

**Comment by infernalsirius** [comment] 2017-04-26 10:06
I feel a bit stupid right now. I changed the liquid tag in theme.liquid to {{ 'theme.scss' | asset_url | stylesheet_tag }} and it is working now. It was looking for a file that did not exist. It works with the original reference when I remove my import directive though. I would really like to know why.

I can use subfolder by the way. It does not look to be restricted finally.

@ansarizafar and @garethjohnsdesign, could you try changing the file reference please?

**Comment by zinyosrim** [comment] 2017-04-26 11:05
Having the same issue with [materialize.](http://materializecss.com/)
Slate build works and I can see the materialize code in theme.scss. This is the stylesheet tag in the <head> code from theme.liquid including the stylesheet tag: 
 ```
 <!-- Compiled and minified CSS -->
  <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css"-->
 {{ 'theme.scss.css' | asset_url | stylesheet_tag }}
```
The line commented out is the link to the CDN and when uncommented my CSS markups display correctly. My domain: [mandala-dev.myshopify.com](url)

The js part:
```
<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      {{ 'materialize.min.js' | asset_url | script_tag }}
      <!--script type="text/javascript" src="js/materialize.min.js"></script-->

</body>
```
I don't get any errors, but the css has no effect:
<img width="1405" alt="bildschirmfoto 2017-04-26 um 12 51 59" src="https://cloud.githubusercontent.com/assets/17767575/25431067/51719f88-2a7f-11e7-9965-0cad93c594b4.png">
 
This is the result when CDN is used
<img width="1418" alt="bildschirmfoto 2017-04-26 um 12 51 04" src="https://cloud.githubusercontent.com/assets/17767575/25431155/b106d7ec-2a7f-11e7-860d-73f4fd8d7335.png">

For build I had to tweak a bit because materialize has subfolders (see theme.scss). I also got link errors during build but they were gone after fixing the URLs.

[theme.scss.txt](https://github.com/Shopify/slate/files/958135/theme.scss.txt)
[theme.scss.liquid.txt](https://github.com/Shopify/slate/files/958121/theme.scss.liquid.txt)

**Comment by NathanPJF** [comment] 2017-04-26 16:18
I've been doing some testing on my end importing both `semantic.css` and the foundation css (both mentioned at the top of this thread).  I'm getting similar errors as people have been dscribing - Shopify throwing an error `Failed to load resource: the server responded with a status of 422 ()`. 

However, I can still see the whole `theme.scss.liquid` file in my online theme files.  Which means Slate is concatenating correctly and uploading it to the correct environment.  So, my suspicion at this point is that the `theme.scss.liquid` files discussed here are **too large** for the online editor to generate - more info on what that means below.

I'll raise an issue with the online store developers to get more information and report back.  In the meantime, you can include these frameworks as separate CSS resources with no `*.liquid` extension.

```
{{ 'foundation-complete.css' | asset_url | stylesheet_tag }}
{{ 'theme.scss.css' | asset_url | stylesheet_tag }}
```

Note: Did a quick test with importing `normalize.scss` from the `vendor/` folder and it worked fine - so not an issue with Slate itself.

### Context on online editor and assets

If Shopify detects a `*.liquid` extension on a file name it will first run a job to replace all Liquid handlebars (`{{`,  `}}`) with the appropriate content and _then_ create the CSS or JS file.  This process takes time to run and there is a timeout implemented to prevent exceptionally long jobs.  I had a quick chat with a dev and we're going to look into this to see if it is a threshold issue or something else at play.

#### File size comparisons

Some of the frameworks mentioned are larger than we typically run through a `theme.scss.liquid` file.  I have a side-by-side comparison below:

|Name | CSS file | File size (unminified) | 
|---|---|---|
| [Venture theme](https://themes.shopify.com/themes/venture/styles/snowboards) | `theme.scss.css`  | 13.4 KB  |   
| [Semantic](https://semantic-ui.com/introduction/getting-started.html)  | `semantic.css`  | 113 KB  | 
| [Materialize](http://materializecss.com/getting-started.html)  | `materialize.css`  | 26.2 KB  | 
| [Foundation](http://foundation.zurb.com/sites/download.html/) (Complete) | `foundation.css`  | 16.4 KB  | 
| [Foundation](http://foundation.zurb.com/sites/download.html/) (Essentail) | `foundation.css`  | 10.4 KB  | 
* File size based on info in Chrome 's Network tab.

You can see that the Semantic CSS is much larger than the entire stylesheet for the Venture theme.  So I wouldn't find it surprising if it was a timeout issue there.  Foundation, on the otherhand, is of comparable size to Venture's stylesheet.  While adding the framework on top of Venture would double it's size, at first glance it doesn't feel to me as something that should trigger a timeout.

I'll come back when I have more information.

**Comment by zinyosrim** [comment] 2017-04-28 13:04
@NathanPJF Nathan, I doubt it's a large file issue. My CSS has 6375 lines of code. The testament theme almost 8000.

**Comment by thmsmtylr** [comment] 2017-05-03 02:56
Any updates on this? I'm currently experiencing the same issue.

**Comment by zinyosrim** [comment] 2017-05-03 20:46
@NathanPJF maybe it makes sense to change the status from question to bug?

**Comment by infernalsirius** [comment] 2017-05-04 06:13
I'm pretty sure it is not a bug since I've been able to make it work. I've made it work changing the tag reference from "theme.scss.css" to "theme.scss".

The file IS named theme.scss, so I guess Shopify's gulp script is not finding the file when it is transpiling the code. Why it is working when we build the vanilla Slate theme is beyond me, I'm far form being a Gulp expert.

@zinyosrim @thmsmtylr  Did you try changing the reference to theme.scss and importing your css files in that file?

I did import my files that way and it works:
`/*!============== Semantic UI ==============*/
@import url('vendor/semantic-css/semantic.min.css');
@import url('vendor/semantic-css/components/icon.css.liquid');`

I did add some liquid code in the icon file to get the correct icon's path. Here is my repository if you want to check what I'm talking about in context: https://github.com/infernalsirius/shopify_semantic_ui.git

**Comment by zinyosrim** [comment] 2017-05-04 19:22
@infernalsirius you mean like this, right?
 {{ 'theme.scss' | asset_url | stylesheet_tag }}

**Comment by infernalsirius** [comment] 2017-05-04 19:45
Exactly @zinyosrim. You do not import subfolders in your assets right? The CDN does not support subfolders.

**Comment by zinyosrim** [comment] 2017-05-04 19:59
@infernalsirius no, i don't. looked at your repo. my theme structure is like yours. I also have all the framework scss files in the vendor/materialize/components dir.

**Comment by garethjohnsdesign** [comment] 2017-05-04 20:01
I got round this by compiling using Codekit to a css file, then referencing that

**Comment by infernalsirius** [comment] 2017-05-04 20:06
Well, if it's not a bug, there is definitely some information missing about the build process.

**Comment by NathanPJF** [comment] 2017-05-04 23:48
Heyo! I'm back with some information.  I've been speaking with online store devs about scss compilation and the frameworks mentioned in this thread, and here's what I got:

## Timeouts 

For jobs like Sass compilation, Shopify has implemented a timeout of 15 seconds on those jobs.  This includes the task of rendering the file with the proper Liquid.

For the Semantic UI scss @ansarizafar described, this is the most likely reason it is not compiling.  Because the large framework is being imported into `theme.scss.liquid`, it is subject to this limitation.  
Three things about this:
1. We've opened up a conversation internally to move Sass compilation as a background job so it wouldn't be counted against this timeout window.  But no timeline for implementation on this background job.
2. No plans to increase the timeout from 15 seconds.  The priority of the online editor is to give instant feedback to merchants as they customize their theme, so there are constraints in place to help make this happen.
3. I've opened an issue to discuss a way to not always have `*.liquid` style assets: https://github.com/Shopify/slate-tools/issues/57.  If you aren't using Liquid, then there should be an easy way not to have a Liquid file.

## Frameworks

### Foundation

@garethjohnsdesign I opened a separate issue with the devs to talk about what's going on with Foundation CSS.  I've imported the Foundation CSS with Slate and it's working fine in the Editor, but not compiling for storefront.  

* Screenshot of editor: http://take.ms/1y9XG
* Screenshot of storefront: http://take.ms/pUWGT

It's a mystery to us for the time being where the problem is coming from.  An interm fix is to call the assets separately.

```html
{{ 'theme.scss.css' | asset_url | stylesheet_tag }}
{{ 'foundation.css' | asset_url | stylesheet_tag }}
```

### Materialize

@zinyosrim you had written:

> Slate build works and I can see the materialize code in theme.scss.

I tried compiling based on Materialize's Sass link: http://materializecss.com/bin/materialize-src-v0.98.2.zip . I immediately had issues using your `theme.scss.txt` you linked because Slate is encountering the SCSS `@import` directive in those theme files.  (Collapsed in details below)  Did you happen to do a fair bit of filename changes in the vendor files to make it work? 

<details><summary>Walkthrough of errors seen using Sass source from Materialize</summary>

Following what I saw in your `theme.scss.txt` file, I started my `theme.scss` file like this:

```scss
/*================ Materialize  ===========*/
@import url('vendor/materialize/materialize.scss');
// Mixins
// @import url('vendor/materialize/components/prefixer');
@import url('vendor/materialize/components/_mixins.scss');
@import url('vendor/materialize/components/_color.scss');

```

However, I get the following error message regarding importing the partials contained within `materialize.scss`.

```bash
19:13:05] change in src/styles - change theme.scss
[19:13:05] running task - build:css
[19:13:05] Error in plugin 'gulp-cssimport'
Message:
    Cannot find file 'components/mixins' from '/Users/nathanferguson/code/slatevendor/src/styles/vendor/materialize' (includePaths: )
```

This is because `materialize.scss` has a line:

```scss
@import "components/mixins";
```

Slate doesn't support the Scss `@import` directive.  This is mentioned at the top of the `theme.scss` file: "You cannot use native CSS/Sass @imports in this file without a build script"

We use the gulp plugin [gulp-cssimport](https://www.npmjs.com/package/gulp-cssimport) which is wanting something much more specific.  

```scss
@import "components/_mixins.scss";
```

Hence, I'm curious if you went through the files and changed the file names to the more specific ones.

</details>
&nbsp;

### Workaround

I was able to use materialize by importing the [materialize.css zip](http://materializecss.com/bin/materialize-v0.98.2.zip).

* Screenshot of editor: http://take.ms/ZlFBP
* Screenshot of storefront: http://take.ms/jrPPI

```scss
/*================ VENDORS ================*/
@import url('vendor/materialize.css');
```

**Comment by infernalsirius** [comment] 2017-05-05 17:10
Thanks @NathanPJF  for this post! There is much interesting informations in it. It is really appreciated.

**Comment by thmsmtylr** [comment] 2017-05-08 00:07
@NathanPJF Thanks for the update regarding Foundation. I ended up dropping Slate altogether. I found another issue where simple mixins wouldn't compile; very frustrating.

**Comment by whosdustin** [comment] 2017-06-07 11:35
Shopify's Sass compiler is using a forked version `v3.2`. Therefore some new sass features will not compile. The biggest example is the fact that you have to still us `@import url("path/to/style.scss");` instead of `@import "path/to/style";`

**Comment by t-kelly** [comment] 2017-08-24 23:54
Closing this in preference to the summary created by @NathanPJF in #230

**Closed by t-kelly** 2017-08-24 23:54 UTC
Labels: question
