### ISSUE TITLE
CSS loader is not working

### ISSUE THREAD

**Issue by Skoulix** [Shopify/slate#807] opened 2018-10-08 12:50 UTC
### Problem

CSS loader is not working if I use @shopify/slate-tools greater than 1.0.0-beta.7 version

### Replication steps

upgrade to "@shopify/slate-tools": "1.0.0-beta.9",

### More Information

I'm using an additional loader inside the slate.config.js file.

Loader is:
```
{
   test: /\.css$/,
   use: ['style-loader', 'css-loader'],
},
```
If I try to import a css file in a .js file like

`import 'flatpickr/dist/flatpickr.css';`

I'm getting the error
`You may need an appropriate loader to handle this file type.`

The CSS import works fine with @shopify/slate-tools => 1.0.0-beta.7 

Is any change happened with regards to this at the latest slate-tools that overrides this loader and doesn't allow me to use a custom one?

Any feedback is much appreciated.
Thanks in advance.

**Comment by t-kelly** [comment] 2018-10-09 13:44
Duplicate of https://github.com/Shopify/slate/issues/677

As for your fix, see the [release notes for beta.8](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.8) and [this thread](https://github.com/Shopify/slate/issues/541#issuecomment-427694674) for the relevant config names you need to use.

**Closed by t-kelly** 2018-10-09 13:44 UTC

**Comment by Skoulix** [comment] 2018-10-09 13:59
This is awesome, thanks for replying.
It seems I missed that one. Sorry for the duplicate issue.
Thanks!
