### ISSUE TITLE
[Windows] Yarn Start isn't loading in theme.scss nor reloading

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#608] opened 2018-05-29 21:55 UTC
### Problem

I'm trying out Slate V1 on Windows 10 and after running `yarn start`, the store doesn't include `theme.scss` so there are no styles applied. It's also not automatically reloading the window on theme change. After running `yarn deploy` the theme file shows up correctly but then `yarn start` removes it again.

It produces an error:
```
22:31:33 [development]Asset Perform Update to assets/styles/theme.scss.liquid at host mystore.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Theme files may not be stored in subfolders
```

This is a brand-new theme with no changes made to it.

Edit: Also, changes made to `theme.scss.liquid` are reflected in `layout.theme.styleLiquid.scss.css` after a manual reload.

**Comment by lloydstubber** [comment] 2018-05-30 00:12
@ConduciveMammal Fellow Windows dev here. Out of curiosity are you using native Windows shell or the WSL?

Also, what Node/Yarn versions are you running?

**Comment by ConduciveMammal** [comment] 2018-05-30 00:14
I tried it in both native and Git Bash

Not too sure on the versions, Node is 8.11.xx and Yarn will likely be the latest. I can check more tomorrow.

**Comment by lloydstubber** [comment] 2018-05-30 00:27
Ah okay, I'm using the Bash on Windows ([WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)) and haven't run into this issue, although I'll double-check later today and let you know.

**Comment by hcmlopes** [comment] 2018-05-30 02:55
I'm not completely sure if this is related but I have been having similar experience.
'yarn start' seems to not be compiling all scss files correctly.  

When I run the command `yarn start`, my "./dist/assets/" folder structure is as follows: 
```
| - assets
       | - /styles
                | - theme.scss.liquid
       | - layout.theme.styleLiquid.scss.liquid
       | - template.gift_card.js
```
In this case none of the styles are applied

When I run the command `yarn deploy` or `yarn build` there are alot more files in the directory and the styles work as expected.

I have tried and verified this on both Mac OS High Sierra running the latest version of node and npm as well as on Windows 10 running node 8.11.1 and npm 5.8.0

**Comment by lloydstubber** [comment] 2018-05-30 03:55
@hcmlopes Strange... Just tested on High Seirra, Node 9.11.1, Yarn 1.6.0 and seems to be working fine. Potentially try upgrading your Node/Yarn?

**Comment by lloydstubber** [comment] 2018-05-30 08:53
@ConduciveMammal Just tested hot-reloading and looked at the directories on my Windows machine and it's working fine. 

Just to clarify I'm using the Windows Subsystem for Linux as the shell. So all my config/tooling is running through there. Little how-to doc on setting it up [here](https://github.com/lloydstubber/my-wsl-setup) and once it's running it's essentially Ubuntu, so very few 'Mac only' issues arise.

Windows 10
WSL (Ubuntu 16.04.4 LTS)
Node 9.11.1
npm 6.0.0
Yarn 1.6.0-20180513.175 (nightly)

Hope that's helpful!

**Comment by Kehza** [comment] 2018-05-30 12:04
Unfortunately I'm having the same issue.. using yarn deploy or yarn build solves the problem too.

Here's my setup:

Windows 10 
Bash Terminal 
Node 9.4.0
npm 5.6.0
yarn 1.7

**Comment by davemeehan** [comment] 2018-05-30 15:49
Same problem
win 10
bash terminal
node 10.3.0
yarn 1.7.0
npm 6.1.0

**Comment by hcmlopes** [comment] 2018-05-30 16:07
Installed WSL yesterday to test everything. Same issue

Ubuntu 16.04.4
bash terminal
node 10.2.1
npm 6.1.0
yarn 1.7.0

**Comment by lloydstubber** [comment] 2018-05-30 20:49
I can't seem to reproduce this... 

Are Node, npm and Yarn all installed via the WSL rather than the Windows way? E.g.

```
where node
/home/s1dney/.nvm/versions/node/v9.11.1/bin/node`
```
```
where npm
/home/s1dney/.yarn/bin/npm
/home/s1dney/.nvm/versions/node/v9.11.1/bin/npm
```
```
where yarn
/usr/bin/yarn
```
Also, @davemeehan and @hcmlopes my `yarn create` won't work with anything above Node 9.11.1 - could you try on a lower version?

**Comment by davemeehan** [comment] 2018-05-30 21:08
@lloydstubber I'll try that tomorrow when I have time. Someone else did the yarn create on this theme from a linux box with an older version of node.

I do have node, npm and yarn installed in both but I did make sure it was using the WSL:
➜  themes which node
/usr/bin/node
➜  themes which npm
/usr/bin/npm
➜  themes which yarn
/usr/bin/yarn

**Comment by lloydstubber** [comment] 2018-05-30 21:39
Thanks @davemeehan. I potentially would try rolling back to Yarn 1.6 as well. I just had a few issues with `yarn create` with it failing completely until I landed on that version. A little reluctant to go up to 1.7 to be honest!

**Comment by hcmlopes** [comment] 2018-05-31 00:58
@lloydstubber I will try to install all related apps with the same exact versions you posted as working and post what happens here sometime tomorrow.

Just to clarify Node, npm and Yarn all installed via the WSL bash shell and running yarn create slate-theme my-new-theme created a new theme no problem just like it did running on windows side of things

**Comment by ConduciveMammal** [comment] 2018-05-31 11:53
@maxcr `slate` commands use Slate V0, not V1, which this issue is about. That's why it's working for you.

**Comment by davemeehan** [comment] 2018-05-31 16:36
@lloydstubber still having the same issue with the older versions:

➜  moringa which node
/home/dave/.nvm/versions/node/v9.11.1/bin/node
➜  moringa node -v
v9.11.1
➜  moringa which npm
/home/dave/.nvm/versions/node/v9.11.1/bin/npm
➜  moringa npm -v
5.6.0
➜  moringa /home/dave/.nvm/versions/node/v9.11.1/bin/yarn -v
1.6.0
➜  moringa /home/dave/.nvm/versions/node/v9.11.1/bin/yarn start
yarn run v1.6.0
$ slate-tools start
(node:22152) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
✔  Compiled successfully in 8.701s!

⚠  You are about to deploy to the published theme. Continue? (Y/n)
↑  Uploading to Shopify...

[development]: 1 / 89 [--------------------------------------------------------------------]   1 %
^C
➜  moringa /home/dave/.nvm/versions/node/v9.11.1/bin/yarn deploy
yarn run v1.6.0
$ slate-tools build && slate-tools deploy
....
⚠  You are about to deploy to the published theme. Continue? Yes

↑  Uploading to Shopify...

[development]: 5 / 109 [=>------------------------------------------------------------------]   4 %

**Comment by davemeehan** [comment] 2018-05-31 18:35
personally I was able to solve this by copying all the source from theme.scss into a new custom scss file, then import the new scss file inside layout/theme.js:
`import '../../styles/custom.scss';`

**Comment by lloydstubber** [comment] 2018-05-31 23:32
@davemeehan Stupid question but did you run `yarn create slate-theme my-new-theme` with your rolled back versions? Or rolled back and then ran `yarn start` on the initial theme that were created with the later versions?

**Comment by davemeehan** [comment] 2018-06-01 00:16
@lloydstubber the project was created by another dev using an older version of node. I'm not sure which version exactly but I could ask.

I rolled back my versions and just did yarn start on the existing project.

**Comment by lloydstubber** [comment] 2018-06-01 00:37
@davemeehan Ah okay so I think that's where the issue may lie. Try and create a new theme via the WSL with the versions I mentioned and run `yarn start`.

**Comment by dereklimbus** [comment] 2018-06-05 20:53
Has anyone found a solution yet? I encountered the same problem on macOS with latest node, npm, and yarn. 

My current solution is to import `*.scss` into `theme.scss.liquid`. But I don't think it's supposed to be so, because `npm/yarn deploy` works as expected, and the browser is not reloaded automatically using `npm/yarn start`.

**Comment by lloydstubber** [comment] 2018-06-05 23:29
@dereklimbus Have you tried on Node 9x? I have it working both on Windows 10/High Seirra with the following:

Node 9.11.1
npm 6.0.0
Yarn 1.6.0

Also, anytime I forget to switch from Node 10 to 9 before running the `yarn create` I can see a flag saying a package is looking for `Node >= 4 <= 9`. This could be the issue if you're on the latest Node.

**Comment by dereklimbus** [comment] 2018-06-06 09:05
@lloydstubber Thank you for your suggestion. I just tried node 8, 9, and 10, and the problem is the same. Then I tried it on my colleague's mac, there is no problem at all. I guess it's because of my OS, which is still Seirra. In terms of Slate, I think the issue is that scss is not compiled locally. I guess it has something to do with node-sass, but I have no idea how to fix it.

**Comment by Kehza** [comment] 2018-06-06 10:35
Still having the same issue here too, I've tried Yarn 1.6 instead as recommended previously but still no luck. I did a completely new setup with the starter theme, I did notice the following error during the deploy command 

"[development]Asset Perform Update to assets/styles/theme.scss.liquid at host cwsellorsdiamonds.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Theme files may not be stored in subfolders"

**Comment by Kehza** [comment] 2018-06-06 12:40
Follow on from this, I've also tried reverting to an older version of node (9.1.0 - what a nightmare that was!) still no luck - any help would be greatly appreciated :(

**Comment by hcmlopes** [comment] 2018-06-06 18:12
I've had not been able to revert to older versions of node under the WSL with ubuntu...sry I wish I could help further

**Comment by dereklimbus** [comment] 2018-06-08 12:56
I solved my problem, please take a look at #414.

**Comment by chrisberthe** [comment] 2018-06-11 14:42
@Kehza is this right after generating a new Slate theme with `yarn create slate-theme whatever`? Probably not related, but curious what version of `@shopify/slate-tools` you have installed in your project's `node_modules` folder.

**Comment by Kehza** [comment] 2018-06-15 08:57
@chrisberthe That is correct, I've tried it a few times from scratch too. According to the "package.json" file within that folder I'm on version "1.0.0-beta.2". I'll be trying dereklimbus's solution shortly.

**Comment by Kehza** [comment] 2018-06-15 12:01
@chrisberthe @dereklimbus That appears to have worked this time, which is weird because I put an exception down for the SSL certificate before as per the instructions. I do have WAMP installed, and was probably running it at the same time so maybe there was a conflict. 

I didn't realise that the assets were saved locally, I assumed they would appear in the "dist" folder, and be automatically uploaded to Shopify - but for performance reasons this makes sense :) 

Thanks for all your help!

**Comment by PolarisTLX** [comment] 2018-11-20 05:30
`yarn start` also not working for me.  It looks like it is running but any changes I make to my Slate project will not show up in my browser.  Only way to make the changes show up is by running `yarn deploy` each time which is extremely inefficient.  

Ubunto 16 (Mint)
Yarn v1.10.1
node v8.11.1
npm  v5.6.0

Any help appreciated.

**Comment by t-kelly** [comment] 2018-11-21 16:30
I cannot reproduce the original bug mentioned in this thread with the latest version of Slate and Starter Theme.

This thread has become wild with multiple topics. Going to lock it. @PolarisTLX your problem is unrelated to the original topic of this thread, please create a new issue. Thanks!

**Closed by t-kelly** 2018-11-21 16:30 UTC
Labels: !, bug, v1.x, windows
