### ISSUE TITLE
Path error on "yarn start"

### ISSUE THREAD

**Issue by kpow** [Shopify/slate#499] opened 2018-04-18 15:31 UTC
### Problem

Can't find server.pem file

### Replication steps

yarn start

### More Information

`/node_modules/@shopify/slate-tools/tools/dev-server/ssl/index.js:6
    : readFileSync(path.join(__dirname, './server.pem'));`

**Comment by ArnauRius** [comment] 2018-04-18 15:35
me too!

**Comment by t-kelly** [comment] 2018-04-18 15:43
Duplicate of #496 and #492

**Closed by t-kelly** 2018-04-18 15:43 UTC
Labels: duplicate
