### ISSUE TITLE
Reviews only partially loading via localhost livereload build

### ISSUE THREAD

**Issue by curiouscrusher** [Shopify/slate#213] opened 2017-08-08 19:01 UTC
### Problem

Hi there, been using Slate for a theme build, and ran into a bit of an issue with the product reviews. When viewing a Product page via the `https://localhost:3000/` livereload url, only a portion of the reviews section loads. However when viewing on the `.myshopify.com` url it works fine.

### Scope

Related to Slate's livereload/localhost functionality.

### Replication steps

1. Create a Slate theme
2. Add a product
3. Install the reviews app & follow snippet instructions
4. View the product page via `https://localhost:3000/` without any reviews the entire block will be missing. 
5. View via `.myshopify.com` url and review form will be visible.
6. Write a review via the `.myshopify.com` url and approve in admin
7. View the page via `https://localhost:3000/` and the average rating block will now be visible, yet form and reviews won't

### More Information
Get 401 on these urls
`https://productreviews.shopifycdn.com/proxy/v4/reviews/badges?callback=jQuery110204489503446597316_1502218188928&shop=localhost%3A3000&product_ids%5B%5D=11307735884&_=1502218188929 `

`https://productreviews.shopifycdn.com/proxy/v4/reviews/product?callback=jQuery110204489503446597316_1502218188926&product_id=11307735884&version=v4&shop=localhost%3A3000&_=1502218188927 `

Adding some screenshots of the console errors and frontend

This is the view from the `.myshopify.com` url
![myshopifycom-frontend](https://user-images.githubusercontent.com/4745854/29089345-90e20824-7c41-11e7-9f2c-874f0d9bca78.png)

View from the `https://localhost:3000/` url
![all-that-shows-frontend-localhost](https://user-images.githubusercontent.com/4745854/29089346-90e46e16-7c41-11e7-9d7d-65eab8e88a73.png)

Console errors
![detailed-load-error](https://user-images.githubusercontent.com/4745854/29089343-90df0796-7c41-11e7-8596-925417e4cdcf.png)

Console errors
![console-errors](https://user-images.githubusercontent.com/4745854/29089344-90e1d1ba-7c41-11e7-94ae-54376ad7bdfe.png)

**Comment by t-kelly** [comment] 2017-08-09 13:42
Looks like an authentication error with your review service and `localhost`. Are there any settings in your review app to add authorized domains?

Closing this as it is not a bug with Slate. Please continue to post though and I'll do whatever I can to help 😄

**Closed by t-kelly** 2017-08-09 13:42 UTC

**Comment by curiouscrusher** [comment] 2017-08-09 20:25
Hi there Thomas, 

Here's all the settings that are available in the Shopify Reviews app, not seeing any authorized domain settings, unless there's an additional page elsewhere(?)

Cheers!


![shopify-review-app-settigns](https://user-images.githubusercontent.com/4745854/29142223-dc621084-7d16-11e7-89ec-8c9807142eff.jpg)

**Comment by oscarpan** [comment] 2017-09-19 00:20
@curiouscrusher I just had the same issue and I solved it by adding in the Shopify shop in the HTML:
```
<script type="text/javascript">
    //<![CDATA[
    var Shopify = Shopify || {};
    Shopify.shop = "...................myshopify.com";
```

**Comment by curiouscrusher** [comment] 2017-10-04 18:34
@oscarpan That looks promising, but could you provide a little more detail on where you added this? Just in the `product.liquid`, `theme.liquid`, or somewhere else entirely? 
And did you encounter any adverse side effects by essentially binding the Shopify var to your store? 

Thanks!

**Comment by oscarpan** [comment] 2017-10-08 22:46
@curiouscrusher on any of the pages you're using the reviews plugin, so if its just PDP then product.liquid or theme.liquid if you have it on other pages. If you put it far up in the head enough, it'll just get overwritten by Shopify's own variable. If you look closely, it only sets the shop attribute and doesn't overwrite the whole Shopify variable. It uses the same format that shopify generates, if you check out the source of your live site, you'll get what I mean.

**Comment by edu2004eu** [comment] 2018-04-17 15:02
Sorry to dig this up, but I have a bit more information:

It seems that the SPR app is checking against your store (maybe even making calls to it). Now if you look into the page source (while running on localhost), you'll see that `Shopify.shop = "localhost:3000";`. This means that SPR can't really check your shop for whatever they need (because obviously your localhost isn't the same as the server which SPR runs on). So as @oscarpan said, overwrite the `Shopify.shop` property and you should be golden. Just make sure to add the line lower in the source code than what shopify already inserts, otherwise your code will get overwritten, instead of the other way.
