### ISSUE TITLE
Why are stylesheets being removed on build/start/deploy?

### ISSUE THREAD

**Issue by Aly-76** [Shopify/slate#887] opened 2018-11-23 12:28 UTC
### Problem

*I am unable to see any compiled stylesheets or any new stylesheets in the dist folder after I run a build or deploy when using Slate 0.14.0*

### Replication steps

*I have followed these steps based on the documentation on the wiki*

npx create-slate-theme myshop
Edit the .env file addeding correct URL/Password/ThemeID/Files to be ignored (settings_data.json)
npm start (This opens locally and asks if I wish to deploy to Shopify - I select yes)
Everything in src > styles is ignored and not compiled into my dist folder apart from a blank theme.scss.liquid which states // removed by extract-text-webpack-plugin

Alternatively I try to run;
slate-tools build (Fails as it's not recognised as a command)
npm build (Fails as it's also not recognised as a command)
npm run-script build (This runs and removes the dist folder then re-adds it the second time I enter it into the terminal)

However, I hit the same problem in that there are no styles compiled from src to dist. 

### More Information

https://screenshots.firefox.com/Md9dFtNj9iDZrBpj/null

**Comment by huguestennier** [comment] 2018-11-23 18:47
When developing, Slate uses Hot Module Replacement which enable faster development workflow. 

Hot Module Replacement (or HMR) inject your styles inline on your page. No CSS will be compiled in a separate file on `yarn start`.

The file `dist/styles/theme.scss.liquid` you see was a regression that was fixed in [v1.0.0-beta.14](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.14).

**Comment by huguestennier** [comment] 2018-11-26 14:47
When you run the `build` command, your CSS will be compiled inside the `dist/assets` folder.

**Comment by t-kelly** [comment] 2018-12-13 15:20
Closing because it looks like this was answered.

**Closed by t-kelly** 2018-12-13 15:20 UTC
Labels: question
