### ISSUE TITLE
Error in plugin 'gulp-cssimport'

### ISSUE THREAD

**Issue by mattsince87** [Shopify/slate#320] opened 2017-10-11 21:21 UTC
*Upgraded theme from ThemeKit to Slate using `slate migrate`.*

I run `slate watch` and my preview works great, but as soon as i go to make changes to my Sass i get the following error above.

````
[22:07:13] change in src/styles - change _gmrui.scss
[22:07:13] running task - build:css
[22:07:13] Error in plugin 'gulp-cssimport'
Message:
    Cannot find file 'gmrui/globals' from '/Users/matt/Documents/Work/NiP/nip-shop/src/styles' (includePaths: )
/Users/matt/Documents/Work/NiP/nip-shop/node_modules/@shopify/slate-tools/lib/tasks/includes/utilities.js:49
    undefined.emit('end');
             ^

TypeError: Cannot read property 'emit' of undefined
    at DestroyableTransform.errorHandler (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/@shopify/slate-tools/lib/tasks/includes/utilities.js:49:14)
    at emitOne (events.js:120:20)
    at DestroyableTransform.emit (events.js:210:7)
    at onwriteError (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:421:12)
    at onwrite (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/matt/Documents/Work/NiP/nip-shop/node_modules/gulp-cssimport/gulp-cssimport.js:96:7
    at DestroyableTransform.fileContents [as _transform] (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/gulp-cssimport/gulp-cssimport.js:118:6)
    at DestroyableTransform.Transform._read (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (/Users/matt/Documents/Work/NiP/nip-shop/node_modules/readable-stream/lib/_stream_readable.js:612:20)
````

### More Information

*Slate Version 0.12.1*

My project contains several sub files that use `partials` in them, a couple of the sub directories have one more sub directory again eg. `src/styles/gmrui/mixins/`.

````
dist/
node_modules/
src/
├── assets/
├── config/
├── icons/
├── locales/
├── scripts/
├── sections/
├── snippets/
├── styles/
│   ├── gmrui/
│   ├── nipab/
│   ├── slick/
│   ├── susy/
│   ├── vendor/
│   ├── _gmrui.scss
│   ├── _normalize.scss
│   ├── _su.scss
│   ├── _susy.scss
│   ├── _susyone.scss
│   ├── theme.scss
└── templates/
*.gitignore
config.yml
*deploy.log
package-lock.json
package.json
README.md
````

**Comment by NathanPJF** [comment] 2017-10-23 21:53
> My project contains several sub files that use partials in them,

@mattsince87 I expect this is where your issue is.  The build process used in Slate has Shopify do all the compiling of Sass so folks can use Liquid tags in their stylesheets.

As noted in the [public docs on using Sass](https://shopify.github.io/slate/theme-scaffold/#sass-helpers):

> Slate does not compile Sass to CSS. Slate uploads .scss files to your theme's /assets directory and compilation is done by Shopify. Shopify is using a forked version of Sass v3.2 which does not support importing partial Sass files with the @import directive.

**Comment by NathanPJF** [comment] 2017-10-23 21:54
Going to close this, but please let me know if you suspect the issue is not related to importing partials.

**Closed by NathanPJF** 2017-10-23 21:54 UTC
