### ISSUE TITLE
Add migration guide for 0.x to 1.x

### ISSUE THREAD

**Issue by jappareti** [Shopify/slate#686] opened 2018-07-23 15:35 UTC
The Readme states:

> If you are migrating from using the previous version of Slate, please review the [new documentation](https://github.com/Shopify/slate/wiki) as there are breaking changes.

but I don't see any information about the breaking changes from 0.x to 1.x or how we would go about migrating.

I think it'd be great to have a list of the breaking changes (unless I'm missing it?) as well as the steps on how to migrate from 0.x to 1.x.

**Comment by t-kelly** [comment] 2018-07-30 16:21
Duplicate of https://github.com/Shopify/slate/issues/542

**Closed by t-kelly** 2018-07-30 16:21 UTC
