### ISSUE TITLE
SSL and Browersync issues

### ISSUE THREAD

**Issue by tonyd256** [Shopify/slate#832] opened 2018-10-15 18:58 UTC
### Problem

When running slate-tools, the localhost:3000 site says it's not secure. I've followed the Wiki instructions on setting up a local cert as well as the solution outlined in the bottom of #726. Also Browsersync is blank. It loads the menu and top nav but the content is just blank. In the console I'm getting these errors: `Failed to load resource: net::ERR_EMPTY_RESPONSE`.

### Replication steps

I'm not sure of replication steps, I simply started a new project.

Here's a screen shot of Browsersync
<img width="1680" alt="screen shot 2018-10-15 at 11 56 24 am" src="https://user-images.githubusercontent.com/1169797/46971625-5de57200-d071-11e8-8515-1eaa6df74d4a.png">

### More Information

I'm new to Shopify and it's development so I could be missing something here.

**Comment by huguestennier** [comment] 2018-10-15 19:02
Duplicate of https://github.com/Shopify/slate/issues/726 and https://github.com/Shopify/slate/issues/761

**Closed by huguestennier** 2018-10-15 19:02 UTC

**Comment by t-kelly** [comment] 2018-10-15 20:39
Just updated the Getting Started guide with [a new step](https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate).
