### ISSUE TITLE
Insufficient permissions when downloading slate

### ISSUE THREAD

**Issue by jeroesguerra** [Shopify/slate#766] opened 2018-09-21 06:27 UTC
PROBLEM

I am trying to upload a new Slate project, but when I use the command ```yarn create slate-theme my-new-them``` I receive this ```success Installed "create-slate-theme@1.0.0-beta.8" with binaries:
      - create-slate-theme```
```error Cannot create "/Users/********/.npm-packages/bin/create-slate-theme" due to insufficient permissions.```

**Comment by t-kelly** [comment] 2018-09-21 10:32
I can't reproduce this on my end since it is a machine permissions issue and is highly dependent on how you have Node/NPM/Yarn installed.

Personally, I have Node/NPM installed via [NVM](https://github.com/creationix/nvm) and Yarn installed via Brew and everything works fine. 

Can't be of much more help so closing.

**Closed by t-kelly** 2018-09-21 10:32 UTC
