### ISSUE TITLE
& parent selector not working properly

### ISSUE THREAD

**Issue by fabianwohlfart** [Shopify/slate#479] opened 2018-04-10 08:14 UTC
### Problem

```
.navigation {
  &--list {
    list-style-type: none;
  }
}
```
causes »Failed to compile SCSS file« in theme.scss

### Replication steps

see above

### More Information

slate v.0.13.0

**Comment by NathanPJF** [comment] 2018-04-10 13:38
This is a duplicate of https://github.com/Shopify/slate/issues/370

From that issue:

> The error you're getting is a result of Shopify using an older version of Sass. As noted in the [Sass helpers section of the docs](https://shopify.github.io/slate/theme-scaffold/#sass-helpers)

Please read that issue for a fuller explanation :)

**Closed by NathanPJF** 2018-04-10 13:38 UTC
