### ISSUE TITLE
cannot import script file from asset directory.

### ISSUE THREAD

**Issue by rabpeter** [Shopify/slate#612] opened 2018-05-31 02:32 UTC
### Problem

*Cannot import custom js file from asset directory*

<script src="{{ '../assets/scripts/vendor/app.js' }} | asset_url"></script>
  This is causing MIME type issue due to timestampe numbers 
  (https://cdn.shopify..... js?234234234242)

also tried to import from static directory 
<script src="{{ 'app.js' }} | asset_url"></script>
This caused 404 error.

And tried to add double quote in the url like  this
<script src="{{ "../assets/scripts/vendor/app.js" }} | asset_url"></script>

**Comment by maxcr** [comment] 2018-05-31 10:49
Did you declare it in `theme.js` first?

```
src/assets/scripts

This folder constains all your JS modules. A theme.js must be present, as it will act as the entry point for your JS application.
```

**Comment by t-kelly** [comment] 2018-06-18 17:48
Duplicate of https://github.com/Shopify/slate/issues/409

**Closed by t-kelly** 2018-06-18 17:48 UTC
Labels: bug, v1.x
