### ISSUE TITLE
JS Bug on addresses.js on the starter theme

### ISSUE THREAD

**Issue by magpiedigital** [Shopify/slate#583] opened 2018-05-22 16:43 UTC
Just wanted to let ya know

```
addresses.js?c700:17 Uncaught TypeError: Shopify.CountryProvinceSelector is not a constructor
    at eval (addresses.js?c700:17)
    at Object../assets/scripts/templates/customers/addresses.js (template.addresses.js:959)
    at __webpack_require__ (template.addresses.js:712)
    at fn (template.addresses.js:95)
    at Object.3 (template.addresses.js:971)
    at __webpack_require__ (template.addresses.js:712)
    at template.addresses.js:764
    at template.addresses.js:767
```

**Comment by t-kelly** [comment] 2018-05-22 17:47
Duplicate of https://github.com/Shopify/starter-theme/issues/74

In the future, please open any issues for Shopify Starter Theme in the[ associated repo](https://github.com/Shopify/starter-theme).

**Closed by t-kelly** 2018-05-22 17:47 UTC
