### ISSUE TITLE
Refuse to apply style 'layout.theme.styleLiquid.scss.css'

### ISSUE THREAD

**Issue by DaveWoody** [Shopify/slate#889] opened 2018-11-23 17:50 UTC
### Problem
Hey i am currently trying to get Slate running in my local environment to develop a shopify theme ( Windows 10 )

I still got an error even though i am using 1.0.0-beta.14 and the styling is completely missing.

**The error:** 
`Refused to apply style from 'https://192.168.x.x:3001/layout.theme.styleLiquid.scss.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Here a screenshot of my site with the starter theme
[Image](https://i.imgur.com/0h2Rrxr.png)

Google Dev Console Error Message
[Image](https://i.imgur.com/eqp9lxr.png)

### Replication steps

*How to replicate the problem. Screenshots or video?*

-  Open a terminal and use the command
`yarn create slate-theme my-new-theme
`
- `cd my-new-theme` and edit the `.env` file with the correct data
- `yarn start` waiting for deploy - got some error messages

[yarn start errors](https://i.imgur.com/dwUfl20.png)

- localhost:3000 opens up with above Google Dev console error messages ( sometimes more 406 errors )

### Additional infos
- https is working 
[https](https://i.imgur.com/YsD3Geo.png)

**Comment by james-prado** [comment] 2018-11-23 18:11
@DaveWoody Did you update `@shopify/slate-tools` to `1.0.0-beta.14` in your package.json?

**Comment by huguestennier** [comment] 2018-11-23 19:19
I just tested with `beta.14` and can't reproduce.

Since there are errors when you run `yarn start`, I'm wondering if this could block `layout.theme.styleLiquid.scss.css` from updating properly? Can you try `yarn zip` and uploading your zip file to your theme?

**Comment by DaveWoody** [comment] 2018-11-24 11:29
When i am using `yarn zip` and uploading the zip to shopify everything looks okay and the stylesheet is being loaded.

[preview](https://i.imgur.com/eNycb9m.png)

**Comment by SaroGFX** [comment] 2018-11-24 16:11
I am having the same problem. I started a new project but it still refuses to apply any style. 

Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
layout.theme.js:1 Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
2(index):1 Refused to apply style from 'https://cdn.shopify.com/s/files/1/0044/9154/2617/t/5/assets/theme.scss.css?7343797218531600009' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Also, is there anyone willing to drop their contact info to help me with questions, because there is a bunch of other things I am confused about regarding slate, such as why there is a big style block in the header, that is not visible in src. It makes me unable to actually build templates as i continuously get stuck with bugs and errors.

**Comment by DaveWoody** [comment] 2018-11-26 14:35
Just wanted to start and that error is present again? I did not change anything..

**Comment by huguestennier** [comment] 2018-11-26 14:43
@SaroGFX Any `net::ERR_CERT_AUTHORITY_INVALID` errors are related to SSL. More info here [how to create a self-signed SSL certificate](https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate)

**Comment by huguestennier** [comment] 2018-11-26 14:45
@DaveWoody schema errors means that you probably changed your `settings_schema.json` and the data doesn't match anymore. You should re-upload `settings_data.json` with data matching the new schema

**Comment by DaveWoody** [comment] 2018-11-26 15:00
I feel stupid. I checked my `package.json` and `@shopify/slate-tools` was not `1.0.0-beta.14` 
I fixed that - rerun `npm install` and no more error messages.

[So it looks like this now.](https://i.imgur.com/C10IOV8.png) without any javascript etc. is that correct now or am i missing something?

**Comment by huguestennier** [comment] 2018-11-26 15:10
Yep. Starter theme has [intentional lack of styles](https://github.com/Shopify/starter-theme#intentional-lack-of-styles). It only serves a starter point - so it ships with as little CSS as possible.

Gonna close this issue now - don't feel stupid 😊

**Closed by huguestennier** 2018-11-26 15:10 UTC
